inherit_from:
  - .rubocop-shared.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'screencast/**/*'
    - 'spec/fixtures/**/*'

Layout/CaseIndentation:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/LineLength:
  Max: 110

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/Output:
  Exclude:
    - spec/spec_helper.rb

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: true
  EnforcedStyle: inline

Style/DoubleNegation:
  Enabled: false

Style/EmptyStringInsideInterpolation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: true
  Exclude:
    - 'lib/cov_loupe/tools/**/*.rb'
    - 'spec/support/mcp_runner.rb'

Style/MultilineBlockChain:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/RedundantFormat:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false
